### ISSUE TITLE
Example for doing things similar to Macro.prewalk

### ISSUE THREAD

**Issue by boxxxie** [RobertDober/traverse#2]
i tried playing around with this lib, and for some stuff it's really nice (the mapper functions are awesome), however i am used to doing thing in a more flexible way (i'm using to things more like Macro.walk)

so, i think that this library can do things just like Macro.walk functions, but it's not immediately obvious how.

so, i guess the most basic thing would be to have traverse run IO.inspect on a piece of data and print out something similar to Macro.prewalk/postwalk.

One task i wanted to do with this lib was to make a function that changes all the keys in a Map from strings to atoms, and it wasn't obvious how to do that.

**Comment by RobertDober** [comment]
Thanks for your feedback.

I will try to play around with your problem set. I wrote this lib because I got confused with Macro.*walk, maybe I should have tried harder to understand it. I did not want to pass the whole datastructure around as an argument too and have more control over the result.

**Comment by RobertDober** [comment]
It is quite easy but there are two gotchas.

1. use `Enum.reduce` to change the keys, Traverse does not touch keys and is not designed to work on flat datatstructures

1. that is more like a slight bug, maybe I can do better with this, `Traverse.mapall`, will not handle the root datastructure, thusly you need to englobe it into a list or tuple, see the test I added [here](https://github.com/RobertDober/traverse/blob/master/test/applications/change_maps/str2atoms_test.exs) for the code

Also N.B. that  in 0.1.2 `Fn.complete_*` will not work in 1.4, I fixed that already for 0.1.3.
